const User = {
	USER_ALL_SUCCESS: "GET_ALL_SUCCESS",
	USER_ALL_ERROR: 'GET_ALL_ERROR',
	USER_BY_NAME_SUCCESS: "USER_BY_NAME_SUCCESS",
	USER_BY_ID: "USER_BY_ID",
	SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
	UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",

	CHANGE_ACTIVE_PAGE: 'CHANGE_ACTIVE_PAGE',

	CHANGE_USER: 'CHANGE_USER',
	SIGN_UP: 'SIGN_UP',
};

const ActionType = {
	User,
};

export default ActionType;