const User = {
	USER_BY_NAME: "USER_BY_NAME",
	SAVE_USER: "SAVE_USER",
	UPDATE_USER: "UPDATE_USER",
	DELETE_USER: "DELETE_USER",
	SAVE_SKILL: "SAVE_SKILL",
	EDIT_SKILL: "EDIT_SKILL",
	DELETE_SKILL: "DELETE_SKILL",
	REPEAT_SKILL: "REPEAT_SKILL",

	SIGN_UP: 'SIGN_UP',
	CLEAR: 'CLEAR',

	REG: 'REG',

	FORGOT_PASSWORD: 'FORGOT_PASSWORD',
	CHANGE_PASSWORD: 'CHANGE_PASSWORD',
	CHANGE_EMAIL: 'CHANGE_EMAIL',
	CHANGE_NOTIFICATION: 'CHANGE_NOTIFICATION',

	SEND_MESSAGE: 'SEND_MESSAGE',

	START_LOADING: 'START_LOADING',

	CHOSE_SKILL_ID: 'CHOSE_SKILL_ID',

	CLEAR_ERROR: 'CLEAR_ERROR',
};

const Page = {
	CHANGE_ACTIVE_PAGE: 'CHANGE_ACTIVE_PAGE',
	HELLO_PAGE: 'HELLO_PAGE',
	MAIN_PAGE: 'MAIN_PAGE',
	ADD_PAGE: 'ADD_PAGE',
	USER_CREATE_PAGE: 'USER_CREATE_PAGE',
	USER_FORGOT_PASSWORD_PAGE: 'USER_FORGOT_PASSWORD_PAGE',
	USER_CHANGE_PASSWORD_PAGE: 'USER_CHANGE_PASSWORD_PAGE',
	USER_CHANGE_EMAIL_PAGE: 'USER_CHANGE_EMAIL_PAGE',
	USER_CHANGE_NOTIFICATION_PAGE: 'USER_CHANGE_NOTIFICATION_PAGE',
	USER_LOGIN_PAGE: 'USER_LOGIN_PAGE',
	USER_ACCOUNT_PAGE: 'USER_ACCOUNT_PAGE',
	USER_SETTINGS_PAGE: 'USER_SETTINGS_PAGE',
	SKILL_PAGE: 'SKILL_PAGE',
	SKILL_EDIT_PAGE: 'SKILL_EDIT_PAGE',
	CONTACT_US_PAGE: 'CONTACT_US_PAGE',
};

const Common = {
	INIT: 'INIT',
	RESET_STATE: 'RESET_STATE',
};

const ActionType = {
	User,
	Page,
	Common,
};

export default ActionType;