const User = {
	USER_ALL_SUCCESS: "GET_ALL_SUCCESS",
	USER_ALL_ERROR: 'GET_ALL_ERROR',
	USER_BY_NAME_SUCCESS: "USER_BY_NAME_SUCCESS",
	USER_BY_ID: "USER_BY_ID",
	USER_BY_ID_SUCCESS: "USER_BY_ID_SUCCESS",
	SAVE_USER_SUCCESS: "SAVE_USER_SUCCESS",
	UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
	DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",

	REPEAT_SKILL_SUCCESS: "REPEAT_SKILL_SUCCESS",

	SIGN_UP: 'SIGN_UP',
	CLEAR: 'CLEAR',

	REG_SUCCESS: 'REG_SUCCESS',

	FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
};

const Page = {
	CHANGE_ACTIVE_PAGE: 'CHANGE_ACTIVE_PAGE',
	MAIN_PAGE: 'MAIN_PAGE',
	ADD_PAGE: 'ADD_PAGE',
	USER_CREATE_PAGE: 'USER_CREATE_PAGE',
	USER_FORGOT_PASSWORD_PAGE: 'USER_FORGOT_PASSWORD_PAGE',
	USER_LOGIN_PAGE: 'USER_LOGIN_PAGE',
	USER_SETTINGS_PAGE: 'USER_SETTINGS_PAGE',
};

const Common = {
	INIT: 'INIT',
	RESET_STATE: 'RESET_STATE',
};

const ActionType = {
	User,
	Page,
	Common,
};

export default ActionType;