const Page = {
	MAIN: "MAIN",
	ADD: "ADD",
	USER_CREATE: 'USER_CREATE',
	USER_LOGIN: 'USER_LOGIN',
	USER_FORGOT_PASSWORD: 'USER_FORGOT_PASSWORD',
	USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD',
	USER_SETTINGS: 'USER_SETTINGS',
};

export default Page;