const Page = {
	MAIN: "MAIN",
	ADD: "ADD",
	USER_CREATE: 'USER_CREATE',
	USER_LOGIN: 'USER_LOGIN',
	USER_FORGOT_PASSWORD: 'USER_FORGOT_PASSWORD',
	USER_CHANGE_PASSWORD: 'USER_CHANGE_PASSWORD',
	USER_CHANGE_EMAIL: 'USER_CHANGE_EMAIL',
	USER_CHANGE_NOTIFICATION: 'USER_CHANGE_NOTIFICATION',
	USER_SETTINGS: 'USER_SETTINGS',
	USER_ACCOUNT: 'USER_ACCOUNT',
	USER_NOTIFICATION: 'USER_NOTIFICATION',
};

export default Page;